[project]
name = "mis"
authors = [{ name = "Made in Syria", email = "support@madeinsyria.example" }]
description = "Made in Syria B2B marketplace Frappe app"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = ["frappe"]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.black]
line-length = 110
