import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const industries = [
  { name: 'Textiles', suppliers: 42, icon: '🧵', desc: 'Apparel, towels, yarn, cotton products, and technical fabrics.' },
  { name: 'Food & Agriculture', suppliers: 37, icon: '🫒', desc: 'Olive oil, grains, canned foods, spices, and agricultural exports.' },
  { name: 'Steel & Metals', suppliers: 31, icon: '🏗️', desc: 'Pipes, profiles, fasteners, industrial parts, and fabricated steel.' },
  { name: 'Plastics', suppliers: 25, icon: '♻️', desc: 'Packaging, films, containers, molded parts, and raw materials.' },
  { name: 'Chemicals', suppliers: 18, icon: '⚗️', desc: 'Industrial chemicals, detergents, coatings, and specialty inputs.' },
  { name: 'Packaging', suppliers: 29, icon: '📦', desc: 'Cartons, tins, labels, flexible packaging, and export packing.' },
];
const stats = ['120+ Suppliers', '5,000+ Products', '45+ Export Markets', '24h Response', '100% Verified'];
const suppliers = [
  { name: 'Damascus Steel Works', industry: 'Steel & Metals', location: 'Damascus', rating: 4.9, years: 26, employees: '250+', exports: 18, featured: true },
  { name: 'Aleppo Textile Co.', industry: 'Textiles', location: 'Aleppo', rating: 4.8, years: 34, employees: '500+', exports: 22, featured: true },
  { name: 'Homs Packaging Group', industry: 'Packaging', location: 'Homs', rating: 4.7, years: 18, employees: '180+', exports: 12, featured: true },
  { name: 'Latakia Food Exports', industry: 'Food & Agriculture', location: 'Latakia', rating: 4.8, years: 21, employees: '130+', exports: 16, featured: false },
];
const products = [
  { name: 'Galvanized Steel Pipe', category: 'Steel & Metals', material: 'Galvanized steel', diameter: '20–160mm', grade: 'ASTM A53', supplier: 'Damascus Steel Works' },
  { name: 'Cotton Terry Towels', category: 'Textiles', material: '100% cotton', diameter: 'N/A', grade: 'Export Grade A', supplier: 'Aleppo Textile Co.' },
  { name: 'Olive Oil Tin Packaging', category: 'Packaging', material: 'Food-grade tinplate', diameter: '1L / 5L / 10L', grade: 'BPA-NI lining', supplier: 'Homs Packaging Group' },
];
const rfqs = [
  { title: 'ERW steel pipes for water project', category: 'Steel & Metals', responses: 5, status: 'Quotes Received', updated: 'Today' },
  { title: 'Private-label cotton towel program', category: 'Textiles', responses: 3, status: 'In Negotiation', updated: 'Yesterday' },
  { title: 'Food tin packaging for GCC export', category: 'Packaging', responses: 2, status: 'Open', updated: 'May 10' },
];
const orders = [
  { id: 'MIS-ORD-1007', party: 'Damascus Steel Works', product: 'Galvanized Steel Pipe', amount: '$18,400', status: 'In Production', date: 'May 12' },
  { id: 'MIS-ORD-1006', party: 'Aleppo Textile Co.', product: 'Cotton Terry Towels', amount: '$7,850', status: 'Shipped', date: 'May 9' },
  { id: 'MIS-ORD-1005', party: 'Homs Packaging Group', product: 'Olive Oil Tin Packaging', amount: '$11,200', status: 'Delivered', date: 'May 1' },
];
const resourceCategories = ['Guides', 'Industry Insights', 'Trade Tips', 'Tools & Templates'];
const resourceCards = ['Global Trade Guide PDF', 'Supplier Verification Checklist', 'Export Packaging Template', 'Syrian Industry Outlook'];

function slug(value) {
  return value.toLowerCase().replaceAll(' ', '-').replace(/[^a-z0-9-]/g, '');
}
function Icon({ children }) { return <span className="icon" aria-hidden="true">{children}</span>; }
function Badge({ children, tone = 'amber' }) { return <span className={`badge ${tone}`}>{children}</span>; }
function PageHeader({ title, text, children }) { return <section className="page-header"><div><p className="eyebrow">Made in Syria B2B</p><h1>{title}</h1><p>{text}</p></div>{children}</section>; }
function Section({ title, eyebrow, children, action }) { return <section className="section"><div className="section-head"><div>{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h2>{title}</h2></div>{action}</div>{children}</section>; }
function Navbar() { return <><div className="announce">Welcome to Made in Syria B2B — verified manufacturers, export support, secure sourcing.</div><nav className="navbar"><a className="brand" href="/"><span className="brand-mark">MIS</span> Made in Syria</a><div className="navlinks"><a href="/industries">Industries</a><a href="/suppliers">Suppliers</a><a href="/search">Products</a><a href="/resources">Resources</a><a href="/about">About</a><a href="/contact">Contact</a></div><div className="nav-actions"><select aria-label="Language"><option>EN</option><option>AR</option></select><select aria-label="Currency"><option>USD</option><option>SYP</option><option>EUR</option></select><a className="ghost" href="/login">Login</a><a className="button" href="/register/buyer">Sign Up</a></div></nav></>; }
function Footer() { return <footer><div><b>Made in Syria B2B</b><p>Connecting global buyers with verified Syrian manufacturers.</p></div><div><a href="/buyer/rfq/new">Submit RFQ</a><a href="/suppliers">Find Suppliers</a><a href="/contact">Support</a></div><div><b>Trust</b><p>Secure platform · verified suppliers · export assistance.</p></div></footer>; }
function Layout({ children, portal = false }) { return <><Navbar /><main className={portal ? 'portal-shell' : ''}>{children}</main><Footer /></>; }
function StatBar({ compact = false }) { return <section className={compact ? 'stats compact' : 'stats'}>{stats.map((stat) => <div key={stat}>{stat}</div>)}</section>; }
function TrustBar() { return <section className="trust">{['Secure Platform', 'Verified Suppliers', 'Export Support', 'Quality Assurance', '24/7 Help'].map((t) => <span key={t}><Icon>✅</Icon>{t}</span>)}</section>; }
function Breadcrumb({ items }) { return <div className="breadcrumb">{items.map((item, i) => <span key={item}>{i ? ' > ' : ''}{item}</span>)}</div>; }
function Tabs({ tabs }) { const [active, setActive] = useState(tabs[0]); return <div className="tabs">{tabs.map((tab) => <button className={tab === active ? 'active' : ''} onClick={() => setActive(tab)} key={tab}>{tab}</button>)}</div>; }
function SupplierCard({ supplier, highlighted = false }) { return <article className={highlighted ? 'card supplier highlighted' : 'card supplier'}><div className="cover"><span>{supplier.industry}</span></div><div className="logo">{supplier.name[0]}</div><div className="card-row"><h3>{supplier.name}</h3><Badge tone="green">Verified</Badge></div><p><Icon>🏭</Icon>{supplier.industry} · {supplier.location}</p><p><Icon>⭐</Icon>{supplier.rating} rating · {supplier.years} years · {supplier.employees} employees · {supplier.exports} export countries</p><div className="badges"><span>Export Ready</span><span>Fast Response</span></div><div className="actions"><a className="button" href={`/suppliers/${slug(supplier.name)}`}>View Profile</a><button className="ghost">Contact Supplier</button></div></article>; }
function ProductCard({ product }) { return <article className="card product"><div className="product-img"><span>{product.category}</span></div><div className="card-row"><h3>{product.name}</h3><Badge tone="green">Verified</Badge></div><p>{product.material} · {product.diameter} · {product.grade}</p><p className="chip">{product.supplier} · ⭐ 4.8</p><div className="actions"><a className="button" href={`/products/${slug(product.name)}`}>View Details</a><button className="ghost">Contact Supplier</button></div></article>; }

function Home() {
  const slides = [
    ['Source industrial products from trusted Syrian suppliers.', 'Compare verified manufacturers, request quotes, and manage global sourcing from one secure platform.'],
    ['Build resilient supply chains with export-ready partners.', 'Find audited companies with certificates, factory capabilities, response-time badges, and market history.'],
    ['Submit one RFQ and receive competitive quotations.', 'Share specs privately, compare offers side-by-side, and convert accepted quotes into orders.'],
  ];
  const [slide, setSlide] = useState(0);
  return <Layout><section className="hero"><div><Badge>Verified Syrian Manufacturing</Badge><h1>{slides[slide][0]}</h1><p>{slides[slide][1]}</p><div className="actions"><a className="button" href="/search">Browse Products</a><a className="ghost light" href="/buyer/rfq/new">Submit RFQ</a></div><div className="dots">{slides.map((_, i) => <button aria-label={`Show slide ${i + 1}`} className={i === slide ? 'active' : ''} onClick={() => setSlide(i)} key={i} />)}</div></div></section><StatBar /><Section title="Industry Categories" eyebrow="Browse by sector"><div className="scroll-row">{industries.map((industry) => <a className="industry-card" href="/industries" key={industry.name}><div className="cover small"><span>{industry.icon}</span></div><h3>{industry.name}</h3><p>{industry.suppliers} suppliers</p></a>)}</div></Section><Section title="Featured Manufacturers" eyebrow="Verified partners" action={<a className="ghost" href="/suppliers">View all</a>}><div className="carousel">{suppliers.filter((s) => s.featured).map((supplier) => <SupplierCard supplier={supplier} highlighted key={supplier.name} />)}</div></Section><TrustBar /></Layout>;
}
function SearchPage() { return <Layout><PageHeader title="Search Products" text="Use precise filters for category, location, material, dimensions, length, and supplier quality."><a className="button" href="/buyer/rfq/new">Can't find it? Submit RFQ</a></PageHeader><div className="searchbar"><select><option>All Categories</option>{industries.map((i) => <option key={i.name}>{i.name}</option>)}</select><select><option>All Locations</option><option>Damascus</option><option>Aleppo</option><option>Homs</option><option>Latakia</option></select><input placeholder="Search pipes, textiles, packaging..." /><button><Icon>🔎</Icon>Search</button></div><div className="chips">{['Verified only', 'Export Ready', 'Steel & Metals'].map((chip) => <button key={chip}>{chip} ×</button>)}</div><div className="content-3"><aside className="sidebar"><h3>Filters</h3><label>Category tree<select><option>All</option><option>Steel & Metals</option></select></label><label>Sub-category<select><option>All</option><option>Pipes</option></select></label><label>Material<input placeholder="Steel, cotton, tinplate" /></label><label>Diameter range<input type="range" min="0" max="200" /></label><h4>Length</h4>{['6m', '12m', 'Custom'].map((x) => <label key={x}><input type="checkbox" /> {x}</label>)}<button className="ghost full">Show More Filters</button></aside><section><div className="toolbar"><p><b>{products.length}</b> matching products</p><select><option>Popular</option><option>Newest</option><option>Rating</option></select></div><div className="grid two">{products.map((product) => <ProductCard product={product} key={product.name} />)}</div><button className="ghost centered">Load More</button></section><aside className="sidebar"><h3>Refine Your Search</h3><ul><li>Add exact grade, standard, and dimensions.</li><li>Choose export-ready suppliers for faster shipping.</li><li>Attach drawings if specs are custom.</li></ul><div className="cta small"><p>Can't find what you're looking for?</p><a className="button" href="/buyer/rfq/new">Submit RFQ</a></div></aside></div></Layout>; }
function Industries() { return <Layout><PageHeader title="Industries & Categories" text="Explore supplier networks by industry and drill into category trees."><StatBar compact /></PageHeader><div className="searchbar"><input placeholder="Search within industries" /><select><option>Sort by supplier count</option><option>A-Z</option></select></div><div className="content-2"><section className="grid three">{industries.map((industry) => <a className="card industry" href="/search" key={industry.name}><div className="cover"><span>{industry.icon}</span></div><h3>{industry.name}</h3><p>{industry.desc}</p><p><b>{industry.suppliers}</b> suppliers</p><b>Explore →</b></a>)}</section><aside className="sidebar"><h3>Why Source by Industry?</h3><ul><li>Compare specialized suppliers faster.</li><li>Match certifications and export markets.</li><li>Request assistance when a category is missing.</li></ul><a className="button full" href="/contact">Request Assistance</a></aside></div></Layout>; }
function Suppliers() { return <Layout><PageHeader title="Supplier Directory" text="Find verified, export-ready manufacturers and contact them directly." /><div className="searchbar"><select><option>Category</option></select><select><option>Location</option></select><select><option>Verification</option></select><select><option>Export Ready</option></select></div><Section title="Featured Manufacturers"><div className="grid three">{suppliers.filter((s) => s.featured).map((supplier) => <SupplierCard supplier={supplier} highlighted key={supplier.name} />)}</div></Section><Section title="All Suppliers"><div className="grid three">{suppliers.map((supplier) => <SupplierCard supplier={supplier} key={supplier.name} />)}</div></Section><TrustBar /><section className="cta"><h2>Ready to find the right manufacturer?</h2><div className="actions"><a className="button" href="/buyer/rfq/new">Submit RFQ</a><a className="ghost light" href="/about">Learn More</a></div></section></Layout>; }
function SupplierProfile() { const supplier = suppliers[0]; return <Layout><Breadcrumb items={['Home', 'Suppliers', supplier.name]} /><section className="profile-hero"><div className="cover wide"><span>Factory cover image</span></div><div className="profile-title"><div className="logo large">{supplier.name[0]}</div><div><h1>{supplier.name}</h1><p>{supplier.industry} · {supplier.location} · Established 1998 · {supplier.employees} employees</p><div className="badges"><span>Verified</span><span>Export Ready</span><span>24h response</span><span>On-time delivery</span></div></div></div></section><section className="kpi-strip">{['26 Years Exp', '18 Export Countries', '24 Products', '250+ Employees', '96% On-time Delivery', '100% Quality Guarantee'].map((kpi) => <div key={kpi}>{kpi}</div>)}</section><div className="content-2"><section><Tabs tabs={['About Us', 'Products (24)', 'Certificates', 'Capabilities', 'Factory', 'Quality Control', 'Export Markets', 'Reviews (18)']} /><article className="card"><h2>About Us</h2><p>Detailed company description, factory video/image area, production capabilities, export experience, certifications, and quality-control story.</p><div className="gallery">Factory video / image</div></article><div className="grid two">{products.map((product) => <ProductCard product={product} key={product.name} />)}</div></section><aside className="sidebar sticky"><h3>Company Info</h3><p>Type: Manufacturer</p><p>HQ: Damascus, Syria</p><p>Export: 65% of production</p><p>Markets: GCC, Europe, North Africa</p><p>Certifications: ISO 9001, CE</p><hr /><h3>Request a Quick Quote</h3><button className="button full">Request Quotation</button><button className="ghost full">Chat Now</button><button className="ghost full">Send Inquiry</button><button className="ghost full">Add to Favorites</button></aside></div></Layout>; }
function ProductPage() { const product = products[0]; return <Layout><Breadcrumb items={['Home', 'Products', product.category, 'Pipes', product.name]} /><div className="content-2"><section><article className="card"><div className="gallery"><span>Main image + thumbnails · zoom · 1/6</span></div><div className="card-row"><h1>{product.name}</h1><Badge tone="green">Verified Product</Badge></div><div className="actions"><button className="ghost">Download Brochure</button><button className="ghost">Add to Compare</button></div><SpecTable product={product} /><Tabs tabs={['Product Description', 'Specifications', 'Applications', 'Packaging & Delivery', 'Certificates', 'FAQ', 'Reviews (8)']} /><p>Long-form product description, applications, packaging details, certificate downloads, FAQs, and buyer reviews.</p></article><Section title="Related Products"><div className="carousel">{products.map((item) => <ProductCard product={item} key={item.name} />)}</div></Section></section><aside className="sidebar sticky"><h3>Request for Quotation</h3><input placeholder="Quantity" /><select><option>Metric Tons</option><option>Pieces</option></select><select><option>Grade / standard</option><option>ASTM A53</option></select><textarea placeholder="Optional message" /><button className="button full">Request Quotation</button><button className="ghost full">Chat with Supplier</button><hr /><h3>Supplier</h3><p><b>Damascus Steel Works</b> · Verified · Damascus · 26 years · 250+ employees</p><div className="badges"><span>Export Ready</span><span>ISO 9001</span></div><a className="button full" href="/suppliers/damascus-steel-works">View Profile</a><h3>Supplier Response Time</h3><p>Usually responds within 24 hours.</p><h3>Why Choose This Supplier?</h3><ul><li>Verified documents</li><li>Export-ready packaging</li><li>Quality certificates</li><li>Fast quotation workflow</li><li>Reliable delivery history</li></ul></aside></div></Layout>; }
function SpecTable({ product }) { const rows = [['Category', product.category], ['Sub-Category', 'Pipes'], ['Material', product.material], ['Standard', 'ASTM A53'], ['Grade', product.grade], ['Diameter', product.diameter], ['Length', '6m / 12m / custom'], ['Surface', 'Galvanized'], ['Usage', 'Water, construction, industrial'], ['Country of Origin', 'Syria']]; return <table><tbody>{rows.map(([key, value]) => <tr key={key}><th>{key}</th><td>{value}</td></tr>)}</tbody></table>; }
function About() { return <Layout><PageHeader title="About Us" text="Our mission is to make Syrian industrial sourcing transparent, verified, and accessible to global buyers." /><div className="content-2"><section><div className="gallery tall">Mission hero image</div><Section title="Our Values"><div className="grid four">{['Trust & Integrity', 'Quality First', 'Partnership', 'Global Reach'].map((value) => <article className="card" key={value}><h3>{value}</h3><p>Principles that shape supplier verification, buyer support, and marketplace operations.</p></article>)}</div></Section><StatBar /><article className="card"><h2>Our Commitment</h2><p>We support verified trade, supplier discovery, quotation workflows, and long-term buyer-manufacturer partnerships.</p></article></section><aside className="sidebar"><h3>Our Team</h3><p>Marketplace, verification, export, and customer-success specialists.</p><button className="button full">Meet the Team</button></aside></div></Layout>; }
function Contact() { return <Layout><PageHeader title="Contact Us" text="Send a message, request support, or get sourcing assistance." /><div className="content-2"><form className="card"><h2>Send a Message</h2><input placeholder="Full Name" /><input placeholder="Email" /><select><option>Subject</option><option>Supplier Support</option><option>Buyer RFQ Help</option></select><textarea placeholder="Message" /><button className="button">Send</button></form><aside className="sidebar"><h3>Head Office</h3><p>Damascus, Syria</p><p>support@madeinsyria.example</p><p>+963 000 000 000</p><p>Sun–Thu, 9:00–17:00</p><h3>Follow Us</h3><p>LinkedIn · Facebook · X</p><div className="map">Embedded map</div><button className="ghost full">Get Directions</button><h3>FAQ</h3>{['How are suppliers verified?', 'Can I submit one RFQ to many suppliers?', 'Do you support export documents?', 'How do messages work?'].map((q) => <details key={q}><summary>{q}</summary><p>Our support team can help with this topic.</p></details>)}</aside></div></Layout>; }
function Resources() { return <Layout><PageHeader title="Resources" text="Guides, insights, trade tips, and templates for international sourcing." /><section className="featured-resource"><div><Badge>Featured</Badge><h2>Global Trade Guide PDF</h2><p>A practical guide to RFQs, supplier verification, export readiness, and order follow-up.</p><button className="button">Download</button></div></section><Tabs tabs={resourceCategories} /><div className="grid four section-pad">{resourceCards.map((title, i) => <article className="card" key={title}><div className="cover"><span>{resourceCategories[i % resourceCategories.length]}</span></div><Badge>{resourceCategories[i % resourceCategories.length]}</Badge><h3>{title}</h3><p>Short resource description with helpful buyer or supplier guidance.</p><button className="ghost">{i === 0 ? 'Download' : 'Read More'}</button></article>)}</div></Layout>; }
function Auth({ role = 'buyer', login = false }) { return <Layout><div className="auth"><section><h1>{login ? 'Welcome back' : 'Join Made in Syria'}</h1><ul><li>Verified Suppliers</li><li>Secure & Private</li><li>24/7 Support</li><li>{login ? 'Industrial sourcing workspace' : 'Connect, quote, and grow your business'}</li></ul><div className="gallery">Industrial imagery</div></section><form className="card"><h2>{login ? 'Login' : 'Create Your Account'}</h2>{!login && <div className="role"><a className={role === 'buyer' ? 'active' : ''} href="/register/buyer">Buyer</a><a className={role === 'supplier' ? 'active' : ''} href="/register/supplier">Supplier</a></div>} {!login && <><input placeholder="Full Name" /><input placeholder="Company Name" /><input placeholder="Phone (+963)" /></>} {role === 'supplier' && !login && <><select><option>Industry</option>{industries.map((i) => <option key={i.name}>{i.name}</option>)}</select><input placeholder="Website (optional)" /></>}<input placeholder="Email" /><input placeholder="Password" type="password" />{!login && <><input placeholder="Confirm Password" type="password" /><div className="password-list">✓ 8+ characters · ✓ number · ✓ special character</div></>} {login && <a href="/login">Forgot Password?</a>}<label><input type="checkbox" /> {login ? 'Remember me' : 'Accept terms and conditions'}</label><button className="button full">{login ? 'Login' : 'Create Account'}</button><button className="ghost full" type="button">Continue with Google</button><button className="ghost full" type="button">Continue with Microsoft / LinkedIn</button>{login ? <a href="/register/buyer">Create an account</a> : <a href="/login">Already have an account?</a>}</form></div></Layout>; }
function Portal({ kind = 'buyer', page = 'dashboard' }) { const nav = kind === 'buyer' ? ['Dashboard', 'My RFQs', 'Received Quotes', 'Orders', 'Suppliers', 'Favorites', 'Messages', 'Saved Searches', 'Profile Settings'] : ['Dashboard', 'Company Profile', 'Products', 'RFQs', 'Quotes', 'Orders', 'Messages', 'Analytics', 'Marketing Tools', 'Leads', 'Reviews', 'Subscription', 'Settings']; return <Layout portal><aside className="portal-nav"><div className="company-chip"><div className="logo">{kind === 'buyer' ? 'B' : 'S'}</div><div><b>{kind === 'buyer' ? 'Buyer Portal' : 'Damascus Steel Works'}</b><small>{kind === 'supplier' ? 'Verified Supplier' : 'Buyer'}</small></div></div>{nav.map((n) => <a href={`/${kind}/${slug(n).replace('my-', '').replace('profile-', '')}`} key={n}>{n}</a>)}</aside><section className="portal-main"><div className="topbar"><div><h1>{humanTitle(page)}</h1><p>Language: EN · Currency: USD · May 12–18, 2024</p></div><div className="actions"><a className="button" href="/buyer/rfq/new">+ New RFQ</a><Badge tone="green">{kind}</Badge><span>🔔</span></div></div><PortalContent kind={kind} page={page} /></section></Layout>; }
function PortalContent({ kind, page }) { if (page === 'rfq-new') return <Wizard />; if (page.includes('messages')) return <Messages kind={kind} />; if (page.includes('analytics')) return <Analytics />; if (page.includes('products')) return <ProductsManage />; if (page.includes('profile') || page.includes('settings')) return <SettingsPage supplier={kind === 'supplier'} />; if (page.includes('subscription')) return <Subscription />; if (page.includes('favorites')) return <Favorites />; if (page.includes('orders')) return <OrdersPage supplier={kind === 'supplier'} />; if (page.includes('rfqs')) return <RFQPage supplier={kind === 'supplier'} />; return <Dashboard kind={kind} />; }
function Dashboard({ kind }) { const kpis = kind === 'buyer' ? ['Total RFQs', 'Quotes Received', 'Active Orders', 'Completed Orders'] : ['Profile Views', 'Total RFQs Received', 'Quotes Sent', 'Orders Received', 'Revenue USD']; return <><div className="kpis">{kpis.map((kpi, i) => <article className="card" key={kpi}><Icon>📊</Icon><h3>{kpi}</h3><b>{[18, 42, 7, 31, '$84k'][i]}</b><a>View All</a></article>)}</div><div className="grid two"><Table title="Recent RFQs" rows={rfqs} cols={['title', 'category', 'responses', 'status', 'updated']} /><article className="card"><h3>RFQ Status Overview</h3><div className="donut">Open · Quotes Received · In Negotiation · Closed</div></article><article className="card"><h3>{kind === 'supplier' ? 'Quote Performance' : 'Recent Quotes Received'}</h3><ul>{suppliers.slice(0, 3).map((s, i) => <li key={s.name}>{s.name} · RFQ response · ${[12000, 8400, 5100][i]}</li>)}</ul></article><Table title={kind === 'supplier' ? 'Top Products Performance' : 'My Orders'} rows={orders} cols={kind === 'supplier' ? ['product', 'amount', 'status', 'date'] : ['id', 'party', 'status', 'date']} /></div></>; }
function Wizard() { return <div className="content-2"><aside className="sidebar"><h3>Why Submit an RFQ?</h3><ul><li>Reach matching suppliers.</li><li>Keep specs confidential.</li><li>Compare quotes side-by-side.</li></ul><Badge tone="green">Secure & Confidential</Badge><button className="ghost full">Contact Support</button></aside><form className="card"><h2>RFQ Submit Wizard</h2><div className="steps"><span>1 RFQ Details</span><span>2 Product & Specifications</span><span>3 Business Details</span><span>4 Review & Submit</span></div><input placeholder="RFQ Title" /><div className="form-grid"><select><option>Category</option></select><select><option>Subcategory</option></select><select><option>Quantity Type</option></select><input placeholder="Required Quantity + unit" /><input placeholder="Target Price (optional)" /><input placeholder="Delivery Location" /><input type="date" /></div><textarea maxLength="1000" placeholder="Product Description (character count)" /><div className="dropzone">Attach Drawings/Files (PDF/DWG/JPG/PNG, max 10MB)</div><button type="button" className="ghost">+ Add Specification</button><textarea placeholder="Business Details: company, country, buyer type, annual purchase volume" /><div className="summary">Review summary with Edit links per section.</div><button type="button" className="ghost">Save Draft</button><button className="button">Submit RFQ</button></form></div>; }
function RFQPage({ supplier }) { return <div className="grid two"><article className="card"><Tabs tabs={supplier ? ['All', 'New', 'Quoted', 'In Negotiation', 'Closed'] : ['All', 'Open', 'Quotes Received', 'In Negotiation', 'Closed']} /><Table title={supplier ? 'RFQs Received' : 'My RFQs'} rows={rfqs} cols={['title', 'category', 'responses', 'status', 'updated']} /></article><article className="card"><h3>RFQ Detail / Quote Comparison</h3><p>Summary card: category, quantity, delivery, date, and status.</p><ul>{suppliers.slice(0, 3).map((s, i) => <li key={s.name}>{s.name} · ${[11800, 12400, 12150][i]} · {7 + i} day lead time · <button className="ghost">View Quote</button></li>)}</ul><button className="button">Compare Quotes</button><table><tbody><tr><th>Price</th><td>$11,800</td><td>$12,400</td></tr><tr><th>Lead Time</th><td>7 days</td><td>9 days</td></tr><tr><th>Accept</th><td><button className="button">Accept</button></td><td><button className="ghost">Accept</button></td></tr></tbody></table>{supplier && <QuotationForm />}</article></div>; }
function QuotationForm() { return <form className="quote-form"><h3>Submit Quotation</h3><input placeholder="Unit Price" /><input placeholder="Currency" /><input placeholder="Total" /><input placeholder="Quantity" /><input placeholder="Lead Time (days)" /><input placeholder="Validity (days)" /><textarea placeholder="Notes" /><button className="button">Submit Quote</button></form>; }
function OrdersPage({ supplier }) { return <div className="grid two"><article className="card"><Tabs tabs={['All', 'In Production', 'Shipped', 'Delivered', 'Completed']} /><Table title={supplier ? 'Orders Received' : 'Orders'} rows={orders} cols={['id', 'party', 'product', 'amount', 'status', 'date']} /></article><article className="card"><h3>Order Detail</h3><p>Supplier/buyer info, order specs, payment status, status timeline, tracking number, and invoice actions.</p><div className="timeline"><span>In Production</span><span>Shipped</span><span>Delivered</span><span>Completed</span></div>{supplier ? <><select><option>Update Status</option><option>Shipped</option><option>Delivered</option></select><input placeholder="Tracking Number" /><input placeholder="Carrier" /><button className="button">Generate Invoice</button></> : <button className="button">Download Invoice</button>}</article></div>; }
function Messages({ kind }) { return <div className="messages"><aside className="sidebar"><h3>Threads</h3>{suppliers.slice(0, 3).map((s, i) => <p key={s.name}><span className="avatar">{s.name[0]}</span> {kind === 'supplier' ? `Buyer ${i + 1}` : s.name}<br /><small>RFQ reference · last message · {i + 1} unread · 10:{i}0</small></p>)}</aside><section className="card"><h2>Thread View</h2><p className="bubble">Hello, please review this RFQ and attached drawing.</p><p className="bubble mine">Thanks, quote attached with lead time and validity.</p><p className="attachment">📎 specification.pdf</p><div className="inputbar"><input placeholder="Type message" /><button className="ghost">Attach</button><button className="button">Send</button></div></section></div>; }
function Favorites() { return <div><Tabs tabs={['Saved Suppliers', 'Saved Searches', 'Favorited Products']} /><div className="grid three">{suppliers.slice(0, 3).map((supplier) => <SupplierCard supplier={supplier} key={supplier.name} />)}</div></div>; }
function ProductsManage() { return <div className="grid two"><article className="card"><div className="toolbar"><h2>Products Management</h2><button className="button">+ Add Product</button></div><div className="bulk">Bulk select · publish · unpublish · delete</div><Table title="Products" rows={products} cols={['name', 'category', 'material', 'grade', 'supplier']} /></article><form className="card"><h3>Add/Edit Product</h3><input placeholder="Title" /><select><option>Category</option></select><textarea placeholder="Description (rich text)" /><div className="dropzone">Images drag-and-drop with reorder</div><input placeholder="Specifications key + value" /><input placeholder="Material" /><input placeholder="Standard" /><input placeholder="Grade" /><input placeholder="Dimensions" /><input placeholder="Country of Origin" /><div className="dropzone">Brochure PDF upload</div><label><input type="checkbox" /> Active</label><button className="button">Save Product</button></form></div>; }
function Analytics() { return <div className="grid two"><article className="card"><h3>Profile Views</h3><div className="chart">Line chart · date range filter</div></article><article className="card"><h3>RFQ Conversion Funnel</h3><div className="chart">RFQs Received → Quoted → Accepted → Ordered</div></article><Table title="Product Performance" rows={products} cols={['name', 'category', 'supplier']} /><article className="card"><h3>Revenue & Export Markets</h3><div className="chart">Revenue bar chart + export markets pie chart</div></article></div>; }
function SettingsPage({ supplier }) { return <form className="card"><h2>{supplier ? 'Company Profile Edit' : 'Buyer Profile Settings'}</h2><Tabs tabs={supplier ? ['About', 'Certifications', 'Capabilities', 'Factory', 'Export Markets', 'Contact Persons'] : ['Account Info', 'Company Profile', 'Notification Preferences', 'Language & Currency']} /><input placeholder={supplier ? 'Company Description / Founding Year / Employee Count' : 'Full Name / Email / Phone'} /><textarea placeholder={supplier ? 'Production capacity, equipment list, MOQ, factory video URL, export markets, contacts' : 'Company profile, notifications, preferred language and currency'} /><button className="button">Save Changes</button></form>; }
function Subscription() { return <div className="grid two"><article className="card"><h3>Current Plan</h3><p>Premium · $199/mo · expires Jun 30 · auto-renew enabled.</p><button className="button">Manage Subscription</button></article><article className="card"><h3>Plan Comparison</h3><table><tbody>{['Free', 'Standard', 'Premium'].map((plan) => <tr key={plan}><th>{plan}</th><td>Features + price</td><td><button className="ghost">Upgrade</button></td></tr>)}</tbody></table></article><Table title="Billing History" rows={[{ date: 'May 1', plan: 'Premium', amount: '$199', invoice: 'Download' }]} cols={['date', 'plan', 'amount', 'invoice']} /><article className="card"><h3>Leads & Featured Placement</h3><p>Buyers who viewed/favorited profile and premium placement toggle.</p><label><input type="checkbox" /> Featured Placement</label></article></div>; }
function Table({ title, rows, cols }) { return <article className="table-wrap"><h3>{title}</h3><table><thead><tr>{cols.map((c) => <th key={c}>{humanTitle(c)}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={i}>{cols.map((c) => <td key={c}>{row[c] ?? '—'}</td>)}</tr>)}</tbody></table></article>; }
function humanTitle(value) { return value.split('-').join(' ').split('_').join(' ').replace(/\b\w/g, (m) => m.toUpperCase()); }
function App() { const path = window.location.pathname; const parts = useMemo(() => path.split('/').filter(Boolean), [path]); if (path === '/') return <Home />; if (path === '/search') return <SearchPage />; if (path === '/industries') return <Industries />; if (path === '/suppliers') return <Suppliers />; if (path.startsWith('/suppliers/')) return <SupplierProfile />; if (path.startsWith('/products/')) return <ProductPage />; if (path === '/about') return <About />; if (path === '/contact') return <Contact />; if (path === '/resources') return <Resources />; if (path === '/login') return <Auth login />; if (path === '/register/supplier') return <Auth role="supplier" />; if (path === '/register/buyer') return <Auth role="buyer" />; if (path.startsWith('/buyer/rfq/new')) return <Portal kind="buyer" page="rfq-new" />; if (path.startsWith('/buyer')) return <Portal kind="buyer" page={parts.slice(1).join('-') || 'dashboard'} />; if (path.startsWith('/supplier')) return <Portal kind="supplier" page={parts.slice(1).join('-') || 'dashboard'} />; return <Home />; }

createRoot(document.getElementById('root')).render(<App />);
